### PR TITLE
Add option to customize HeaderControls

### PR DESCRIPTION
**Pull request by vforvasile**
Hi!

By default, it will render the texts provided in nextTitle, previousTitle.

Optional props added:
```
      prevCustomChild={Any}
      nextCustomChild={Any}
      prevCustomStyle={Object} // controls the wrapper of prevCustomChild
      nextCustomStyle={Object} // controls the wrapper of nextCustomChild
```
If children are provided, CalendarPicker will render them inside <Controls />

Updated Readme table and added a new example with custom icons.

Sample:
image

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @vforvasile 👍   This is very useful.  A few questions / comments:
> | **`prevCustomChild`** | `Any` | Optional. Replaces previousTitle with your own custom component (to be used along with prevCustomChild) |

I don't understand the intent of that... prevCustomChild is to be used with prevCustomChild?

The prop names feel confusing.  How about renaming them to prevComponent and nextComponent (and correspondingly, prevComponentStyle and nextComponentStyle).

In cases where there's a ternary, it's clearer if the container remains fixed while the contents are conditional.  For example, in Controls.js:
```
  if (children) {
    return (
      <TouchableOpacity style={styles} onPress={() => onPressControl()}>
        {children}
      </TouchableOpacity>
    );
  }
  return (
    <TouchableOpacity onPress={() => onPressControl()}>
      <Text style={[styles, textStyles]}>{label}</Text>
    </TouchableOpacity>
  );
```

Becomes
```
  let content = children || <Text style={[styles, textStyles]}>{label}</Text>;
  return (
    <TouchableOpacity style={styles} onPress={() => onPressControl()}>
      {content}
    </TouchableOpacity>
  );
```
That makes it apparent that `styles` is doing double duty on the TouchableOpacity and the Text component.  This will be harder to maintain and reason about.  It would be clearer to add an internal prop to Controls.js that separates the custom component style.

This type of approach would also be better in HeaderControls.js where it instantiates `<Controls>`.  Instead of two separate conditional `<Controls>` blocks each, create one that passes in different props.

Did you use prettier / beautifier to auto-format the files?  A number of diffs are only formatting changes.  We should add a .prettier file to standardize formatting and avoid churn on formatting-only changes.

**Comment by vforvasile** [comment]
> I don't understand the intent of that... prevCustomChild is to be used with prevCustomChild?

Hi, I made a mistake typing, prevCustomChild to be used with nextCustomChild and vice-versa, if one child is used with nextTitle or prevTitle the UI will be broken, so I tried to explain that if you used custom components, you don't use the **title** props (gotta fix that).

Agree on the refactor, I didn't want to remove any code at start, just wanted to add my logic on top of existing logic, I'll make some changes by the end of this week and ask for a review from you.

> Did you use prettier / beautifier 
Yes, I use it. This project needs a config for that

Thanks for the suggestions!

**Comment by peacechen** [comment]
@vforvasile  There have been some commits since your PR that caused conflicts.  Would you mind resolving them? (or extract the core of your changes into another PR)

**Comment by peacechen** [comment]
Due to the merge conflicts and other changes that needed to be made, I rewrote this in commit 859f3423d9b5f46dac95ef4fc36f5e2eb7ff3383.

**Comment by vforvasile** [comment]
hey @peacechen, thanks and sorry for not updating my fork!

**Pull request closed without merging**
