### PR TITLE
Adding date range support

### PR DESCRIPTION
**Pull request by ararog**
Any constructive feedback is welcome.

### CODE REVIEW

**Comment by stephy** [comment]
Hey, Sorry I haven't had time to look at this. I am very interested to see what you have added and looking forward to add date range support. I will get on it soon. Thanks in advance.

**Comment by jasongaare** [comment]
@stephy any chance you'd had the chance to review this yet?

**Comment by rdewolff** [comment]
Any update on that?

**Comment by stephy** [comment]
@ararog very cool! Thank you so much for your contribution. I just had time to check the changes. Sorry it took so long. The styles are a little off but I will fix that. Again, your PR is very appreciated.

**Pull request merged**
