### PR TITLE
dayOfWeekStyles should apply When calendar start and customDatesStyle…

### PR DESCRIPTION
**Pull request by prabaperera**
1. CalendarPicker allow to set both dayOfWeekStyles and customDatesStyles. But customDatesStyles has precedence and both properties can not work together. I think, caller should have the control and CalendarPicker should take care of both dayOfWeekStyles and customDatesStyles.

2. CalendarPicker allow to set initialDate and it help to initiate calendar with any arbitary date and it is good. But it does not apply dayOfWeekStyles when initiate.

This request has solution to above both cases.

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @prabaperera for submitting this useful PR.  Couple of points:

I'd like to refactor the logic to make it clearer what's happening.  Every time I read that section of code I have to spend time figuring out what it's trying to do.  Do you mind if I make some edits?

The user has no ability to control whether dayOfWeekStyles or customDatesStyles has precedence if they supply both.  A prop to control that behavior would be help address that.  I can work on that during the refactor.

**Comment by prabaperera** [comment]
> Thanks @prabaperera for submitting this useful PR. Couple of points:
> 
> I'd like to refactor the logic to make it clearer what's happening (not your code, but from a prior PR). Every time I read that section of code I have to spend time figuring out what it's trying to do. Do you mind if I make some edits?
> 
> The user has no ability to control whether dayOfWeekStyles or customDatesStyles has precedence if they supply both. A prop to control that behavior would be help address that. I can work on that during the refactor.

yes. Please go ahead. Let me know, if you need anything from my side.

**Comment by peacechen** [comment]
The cleanup and refactor took more work than I expected.  State change logic shouldn't be in the render() method.  I moved the `dayOfWeekStyles` logic into the `updateDayOfWeekStyles()` method.

I added the `customDatesStylesPriority` prop to control which style takes precedence.  The Readme has been updated to reflect that.

Please test these changes from your fork.  Let me know if you need help on how to pull from your repo into your RN project.

**Comment by peacechen** [comment]
@prabaperera 
I update the sample project under the `example` folder to include `customDatesStyles` & `dayOfWeekStyles`.  You'll need to add this repo as a remote and rebase-pull from it to get the changes.
Alternatively, you could use the sample project code in your app to try it out.

**Comment by peacechen** [comment]
I'm merging this so it doesn't hold up other PRs.  Please validate whether it works as you expect.

**Comment by prabaperera** [comment]
@peacechen your fix has address the issue perfectly. Now it has resoled.

**Pull request merged**
