### PR TITLE
Month and Year Picker closes #150

### LINKED ISSUE #150: Month and year select
Is there a way we can implement a month and a year select? It is a great picker and I'm using it a lot. If this isn't actively being worked on as a feature I will submit a PR to it as I definitely will need this functionality.

### PR DESCRIPTION
**Pull request by CaffeinatedFunctionality**
This allows the user to click on the month or year header and be able to change the month and year. I needed this for birthdays mostly. Clicking previous to get to 1986 is a bit tedious. Let me know if there are any changes you would like and I will handle them.

### CODE REVIEW

**Comment by scy0846** [comment]
Looks like I need to adjust the snapshot. I will do this soon when I have the ability. The snapshot test is a bit new to me.

**Comment by slingshotpeace** [comment]
Thanks for the PR.  Try this to update the snapshot:
`jest --updateSnapshot`

https://jestjs.io/docs/en/snapshot-testing

There are quite a few commits in this PR.  I don't see an update to the Readme to document the new prop.  Is there any way you could squash your commits?  You can force push to your fork and it should update this PR automatically.

**Comment by peacechen** [comment]
Thanks for the PR.  Try this to update the snapshot:
`jest --updateSnapshot`

https://jestjs.io/docs/en/snapshot-testing

There are quite a few commits in this PR.  I don't see an update to the Readme to document the new prop.  Is there any way you could squash your commits?  You can force push to your fork and it should update this PR automatically.

**Comment by scy0846** [comment]
Yeah I think I can get that done tomorrow. I apologize. I meant to update the Readme with the new props and with the new screenshot. This changes the year and month text to buttons so it looks a little different now. I may make some aesthetic changes to make the Month and Year Pickers look a little better in the future as well.

**Comment by peacechen** [comment]
Thanks for the heads up about the buttons.

It would be better if the default style made it look like it used to.  The visual change will cause problems with existing users of the library.  Those who'd like to make the month "button" stand out can use the styling props.

**Comment by scy0846** [comment]
Ok I can make those adjustments

**Comment by razirbel** [comment]
Is this being worked on still?  I could really use this feature.  Thank you

**Comment by peacechen** [comment]
This will need to be refactored, or at least squashed to make it easier to see all the changes. 

@scy0846  Would you mind either squashing the commits in your fork, or create a new PR?

@razirbel  You could also checkout his fork and either squash the commits or copy the code directly into your fork.  Then continue fixing it to resolve conflicts and make sure it's all functional.

**Comment by dquessenberry** [comment]
Any progress on getting this PR merged? I could really use this feature!

**Comment by yadimuhammad** [comment]
so this feature canceled?

**Comment by peacechen** [comment]
This is a community supported library and we need everyone's contributions to provide new features and fixes.  Please consider creating a PR off the current master branch.  You can use CaffeinatedFunctionality's code to get a head start.

**Comment by peacechen** [comment]
@CaffeinatedFunctionality @razirbel @yadimuhammad 

Would someone mind cleaning up this PR?  Please squash into fewer commits and resolve merge conflicts.  It may be easier to create a new PR.  I'll review and merge ASAP.

**Comment by peacechen** [comment]
@CaffeinatedFunctionality @razirbel @yadimuhammad @dquessenberry 

This has been implemented in commit 67a03746500896ab2a8c90421fde71fa5f00d34b .  CaffeinatedFunctionality's PR was a good foundation.  Moving the monolithic year & month selector views out of the root component helped expose some redundancies and unnecessary props.  The root component is already unwieldy  in size, so minimizing its size increase helps with maintainability.
There were some misc improvements in the layout.  The containers needed to stretch to fill the width.  The current year is now centered in the grid which is easier to navigate to adjacent years forward and backward.  The years now increase to the right & down which is consistent with the days (standard LTR language flow).

Please validate this new functionality and post feedback in #150.

**Pull request closed without merging**
