### PR TITLE
Fixes issue #153 (first row is blank)

### PR DESCRIPTION
**Pull request by RohanTalip**
- If startFromMonday is false, startIndex needs to be assigned firstWeekDay modulo 7 (because otherwise if the first week day is Sunday, firstWeekDay is 7 from isoWeekday() and the index variable from guideArray is never >= 7, and so the first row just consists of 7 EmptyDay elements).
- Also split guideArray into dayArray and weekArray, since it is used for both days and weeks, but there can't be 7 rows of weeks in a calendar view for any month.
- Renamed the generateColumns() function to generateDatesForWeek() to better explain what it is doing.
- Removed the unnecessary intermediate "column" constant (it wasn't really being used).
- Renamed the 2 current value "index" variables in the map functions to better describe what they are being used for.
- Added some blank lines and spaces for better readability.

The snapshots in the tests were updated to remove the extra (empty) row that was being added due to the code previously looping over 7 weeks in every month, which has now been changed to 6 weeks.

### CODE REVIEW

**Comment by RohanTalip** [comment]
You may want to merge pull request #156 first, to fix the tests, after which I can fix the tests again for this pull request.

**Comment by RohanTalip** [comment]
I have rebased my pull request and fixed the tests for this change.

**Comment by peacechen** [comment]
This is great @RohanTalip .  How much testing have you done with your changes?  I don't have time to right now to try it out so will have to rely on you.

**Comment by RohanTalip** [comment]
> This is great @RohanTalip . How much testing have you done with your changes? I don't have time to run it right now so will have to rely on you.

I have looked at most months in the last year and up to the end of this year, with startFromMonday both true and false, and they seem valid.

Here are some screenshots of a couple of months that exhibit the fixed behaviour, with startFromMonday=false :

July 2018 - start from Sunday

September 2019 - start from Sunday

The same months, with startFromMonday=true :

July 2018 - start from Monday

September 2019 - start from Monday

And here is the current month, both with startFromMonday=false ... :

June 2019 - start from Sunday

... and startFromMonday=true :

June 2019 - start from Monday

**Comment by RohanTalip** [comment]
Please let me know if there is something else you would like me to test.

Also, should I bump the version number in the package.json file? Maybe to 6.0.1?  Or 6.1.0?

**Comment by peacechen** [comment]
Thanks for testing and sharing screenshots.  I'll bump the version in a separate commit for a release.

**Pull request merged**
