### PR TITLE
Update recyclerlistview to the latest version

### PR DESCRIPTION
**Pull request by jaisongreen**
Update recyclerlistview to the latest version to address high vulnerabilities

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @jaisongreen

Were there any breaking changes in recyclerlistview 4? I'm not able to test this unfortunately. I could publish this as a beta version if you need to use it now.

**Comment by jaisongreen** [comment]
> Thanks @jaisongreen
> 
> Were there any breaking changes in recyclerlistview 4? I'm not able to test this unfortunately. I could publish this as a beta version if you need to use it now.

I am not seeing any breaking changes for recyclerlistview 4+. I tested by running the tests for the CalendarPicker and doing a quick test in iOS and Android.

**Comment by ramonxm** [comment]
this works great

**Comment by peacechen** [comment]
Thanks for your contribution! There's another pending PR that I'd like to merge in addition to this before cutting a new release.

**Pull request merged**
