### PR TITLE
added ability to disable day presses

### PR DESCRIPTION
**Pull request by bmcn99**

### CODE REVIEW

**Comment by peacechen** [comment]
@bmcn99 
Thanks for the PR.  Just want to make sure that this isn't provided by any of the existing props such as `disabledDates`.  If no `onDateChange` prop is provided, nothing is done with the selected dates either.

Is your goal to completely eliminate the selection animation?

**Comment by bmcn99** [comment]
> @bmcn99
> Thanks for the PR. Just want to make sure that this isn't provided by any of the existing props such as `disabledDates`. If no `onDateChange` prop is provided, nothing is done with the selected dates either.
> 
> Is your goal to completely eliminate the selection animation?

Yes I wanted to use the calendar to allow the user to choose a given month, but also show which dates within each month had an event associated with them. I've already forgotten the issue I had with the base project but I thiiiink if you tapped on a specific date it would close the picker, which I didn't want.

**Comment by peacechen** [comment]
Ok that sounds reasonable.  To keep the prop names consistent, would you mind changing the name to `enableDateChange`?

The existing callback prop on date selection is `onDateChange`
https://github.com/stephy/CalendarPicker#calendarpicker-props

**Comment by bmcn99** [comment]
> Ok that sounds reasonable. To keep the prop names consistent, would you mind changing the name to `enableDateChange`?
> 
> The existing callback prop on date selection is `onDateChange`
> https://github.com/stephy/CalendarPicker#calendarpicker-props

OK, I've made that change and it looks like the pull request updated.

**Comment by peacechen** [comment]
Looks good.  Thanks for the PR 👍

**Comment by peacechen** [comment]
Published to npm in 6.0.0

**Pull request merged**
