### PR TITLE
Update Day.js to remove bug in todayTextStyle

### PR DESCRIPTION
**Pull request by jblack128**
update `Day.js` to resolve bug where `selectedDayTextStyle` overwrites `todayTextStyle`

### CODE REVIEW

**Comment by peacechen** [comment]
This is by design. The selected day has its own style to clearly indicate that day is selected, even if the day is "today". The proposed change would break that behavior. How do your users know that "today" is selected if its style doesn't change?

**Comment by jblack128** [comment]
The changes I proposed do still allow for `selectedDayTextStyle`  to change the style of todays date when it is selected. What my changes are doing is when today is not selected the `todayTextStyle` takes priority and will show. 

As the library is right now if `todayTextStyle` is set to `red` and `selectedDayTextStyle` is set to `white` todays date will always be set to the color `white`. 

Here is an example video
Not-Patched

In my proposed changes the `todayTextStyle` is set to `red` and `selectedDayTextStyle` is set to `white` but in the `todayTextStyle` takes priority and will show the text color red unless the day has been selected where it will change to the color set in `selectedDayTextStyle`. 

Here is an example video 
Patched

**Comment by peacechen** [comment]
Thanks for the GIFs of the bug. That makes it very clear what's going wrong. Merging and will cut a release when another pending PR is addressed.

**Comment by jblack128** [comment]
Thanks for the review!

**Pull request merged**
