### PR TITLE
Add feature to disable dates within a range of the selected start date

### PR DESCRIPTION
**Pull request by adpuckett87**

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @adpuckett87 .  This looks good, but the prop name `minRangeDates` doesn't feel as self-explanatory as it could.  I had to read through the code to better grasp what it's doing.  While the name is technically accurate, I feel there's a better name for it.  Just haven't figured one out ;)

**Comment by adpuckett87** [comment]
Yeah, that was my third attempt at a good variable name. What do you think about minSelectableRangeByDate? or minDayRangeByStartDate?

**Comment by peacechen** [comment]
Some other candidates
* minSelectableRanges
* minRangeDays
* minRangeDuration

How would a global minimum range be set?  This PR looks like every date would need to be passed in with minDays specified.

I could see use cases where a max range would be useful too.

**Comment by adpuckett87** [comment]
@peacechen all great ideas, see my latest commit

**Comment by peacechen** [comment]
Good stuff @adpuckett87 !    I don't have time to test this out fully, but will merge it so others can try it out directly from the repo.  When it's gotten some more testing, I'll publish a new version.

**Pull request merged**
