### PR TITLE
replace moment.js with day.js

### PR DESCRIPTION
**Pull request by PizzaLiu**
https://github.com/you-dont-need/You-Dont-Need-Momentjs

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @PizzaLiu for this valuable PR.   There are a number of people using this in their apps who expect to Moment dates.  This will break their apps.  If we decide to do this, there are some paths we could take:

1. Increase the major version and deprecate Moment in favor of Day.js.
2. Support both Moment and Day (could implement a translation layer).

It wasn't that long ago that someone wanted to switch to date-fns.  Now there's Day.js.  Which is "better" ?

Finally, all of the documentation needs to be updated, including the localization section.  Search through the issues and you'll see many people using that feature.  That's one of my main concerns with switching.

**Comment by yuritoledo** [comment]
Moment itself don't have code splitting. If you want to use just one little function of moment - like parse - you need to import all whole heavy library.

Maybe the PR should have a flag: "useDayJs" defaults as false, to be retro-compatible

**Comment by peacechen** [comment]
If Moment doesn't support code splitting, would there be any size savings through a switch flag?  Internally the Moment calls would still be present and thus pulled in to the build.

The biggest hurdle to switching is localization, IMHO.  People are using the library in non-English apps and would have to change their setup.  **This PR needs full documentation for Day JS localization along with examples.**

Day JS timezone support is spotty. Plugins seem to add that feature, but not sure how robust they are.

It looks like minified Moment is 69 kB, whereas DayJS is 2 kB.  Percentage wise that's a big difference, but in raw terms 67 kB isn't hugely significant.  It still may be worth it, but all pieces of the changeover need to be addressed.

**Comment by peacechen** [comment]
There is a project called [date-io](https://github.com/dmtrKovalenko/date-io) which abstracts numerous JS date libraries. This would allow CalendarPicker to support any date library the user chooses.
I will open a new issue to discuss this.

**Pull request closed without merging**
