### PR TITLE
Fix months shifting to use proper date-fns methods and backwards range date selection

### PR DESCRIPTION
**Pull request by giorgiofellipe**
- It was using some weird non-existent date functions, probably left over from moment migration, fixed it to use the proper date-fns ones;
- Also it wasn't working properly the backwards range date selection due to a logic error on date comparison to the previously selected date (that was comparing to the wrong variable);

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks @giorgiofellipe for fixing these bugs. Your contribution helps this project and the open source community.

@tranjog would you mind bumping the version and publishing?

**Comment by tranjog** [comment]
Thanks for fixing this @giorgiofellipe !

@peacechen Sure, can you please merge my PR ? [#372](https://github.com/stephy/CalendarPicker/pull/372),
then I'll publish it.

**Comment by peacechen** [comment]
Done. Thanks @tranjog

**Comment by tranjog** [comment]
Published [8.0.2](https://www.npmjs.com/package/react-native-calendar-picker/v/8.0.2)

**Pull request merged**
