### PR TITLE
Prop disabledDates to disable single or multiple dates

### PR DESCRIPTION
**Pull request by ittikorns**
Add disabledDates prop which allow user to block out specific or multiple dates

### CODE REVIEW

**Comment by peacechen** [comment]
Would be good to define disabledDates as an array in propTypes.

**Comment by ittikorns** [comment]
Add disabledDates as an array into propTypes (thanks @peacechen) and also performs Array.isArray() check before running .map function.

**Comment by peacechen** [comment]
@ittikorns  Would you mind updating this PR to resolve the conflicts?  I can merge PRs now.

**Comment by peacechen** [comment]
PR #104 supersedes this

**Pull request closed without merging**
