### PR TITLE
props to be abble to disable date with a function

### PR DESCRIPTION
**Pull request by t42merli**
From the README

| **`disableFunc`** | `Function` | Optional. Function to disable dates, takes a `moment` Object from the node-module `moment` as  parameter, if the function return true on a date then it is disabled. For example the function `date => (date.day() === 6) || (date.day() === 0)` would disable all weekends. Keep in mind that if the function used is not correct then it will crash, also if the fuction is heavy it may slowdown the app. |

### CODE REVIEW

**Comment by peacechen** [comment]
Thanks for the PR.  I'm hesitant to add a function prop since there's already a `disabledDates` prop that offers this feature.
https://github.com/stephy/CalendarPicker#calendarpicker-props

Another issue I see is that the function may be re-evaluated on certain prop changes, but this may or may not be what the user wants.  If they want to force a re-evaluation, they'll need to change the appropriate props to kick the evaluation.  Since this is the case, it would better to use the `disabledDates` prop instead.

**Comment by t42merli** [comment]
Hello, thank you for your answer.
I thought to be able to use a function would be useful in some case like the example I used with the weekend, it can make quite a big array to use if you want to disable all weekends for the next 10 years for example (unless I've missed something), And the possibility to use this props those not preclude the `disabledDates` one, it's just another feature. 
I'm not really sure I understand your second point since I've not been using js and react for long and my English is not perfect (French), If it is indeed a big problem, then it's still up to you to add the feature or not :). Thanks!

**Comment by peacechen** [comment]
No apologies necessary.  Your English is far better than my French :)

In React, prop changes trigger re-renders.  Without that or some other internal state update, a re-render may not occur which would cause the `disableFunc` value to be stale and incorrect.  I'm uncertain whether this will be an issue with the function prop, but suspect there will be corner cases.

Additionally, if both `disabledDates` and `disableFunc` props are provided, it's unclear which should take priority.  It may be better to refactor this to allow `disabledDates` to accept a function, and switch the logic based on that.

**Comment by SirAnimesh** [comment]
Thanks @t42merli for looking into this. This has been a thorn in my side too.

Hi @peacechen, if you get a chance, could you please clarify the design decision behind going for a `disabledDates` props rather than `enabledDates`. Such a prop would allow me to directly channel all my event dates through to the calendar picker. Currently, I have to get all the dates in an `allDates` array and then filter out those for which I have events. Rather circuitous.

Would you be happy to see a PR that adds `enabledDates` as a prop?

Cheers!

**Comment by peacechen** [comment]
Thanks for the feedback @SirAnimesh .  The assumption was that most of the time the majority of dates are enabled, while disabled dates are sparse.  However this isn't always the case which you have come across.

Are you requesting an `enabledDates` prop, or a date enable/disable function prop?  I lean towards the latter.  Maybe the change would be as simple as changing the func prop to `datesFilter`, and invert the logic so that `true` indicates the date is enable, and of course `false` means it's disabled.  @t42merli would you be willing to make the changes?

**Comment by peacechen** [comment]
I've refactored this to support a function passed to the existing `disabledDates` prop.  Commit 5a45e0a3e3a7a493858ba354aa07c449c13210db

Please test and open a new issue if you find any bugs.  I'll publish a new version after this feature has been validated.

You can pull directly from master by using this in your package.json:
```
    "react-native-calendar-picker": "https://github.com/stephy/CalendarPicker",
```

**Pull request closed without merging**
