### PR TITLE
Add selectedDayColor attribute

### PR DESCRIPTION
**Pull request by thomaswright**
I needed a different color for the selected day, so I added an optional attribute. If not specified, the color defaults to that ios green (#5ce600). Figured this might be useful for others!

### CODE REVIEW

**Comment by joshuapinter** [comment]
Any of change of getting this merged in @stephy? 

I see there's been a lot of forks that people have made with some awesome improvements but the project appears dead. 

Maybe you can have someone take over the library if you're short on time to maintain it. You've done a great job and I'd love to see this keep evolving.

Thanks!

**Comment by stephy** [comment]
@joshuapinter Hi Joshua, I will be updating this repo this week. I hope this helps 👍 Thank you for all your contributions.

**Comment by joshuapinter** [comment]
@stephy That's great, thanks! Looking forward to evolving this.

**Comment by stephy** [comment]
@joshuapinter & @thomaswright, I have added the contents of this PR to the latest NPM package.
I had a lot of conflicts and I had to do some updates so I added it manually. I really appreciate the contribution. I will close this PR for now.

**Comment by joshuapinter** [comment]
Thanks @stephy! 👍

**Comment by thomaswright** [comment]
Cool, thanks @stephy !

**Pull request closed without merging**
